services:

  valmary_backend:
    container_name: valmary_backend
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    build:
      context: app/backend
      dockerfile: ../../docker/backend.Dockerfile
    volumes:
      - ./app/backend:/app
      - ./conn/gcp.json:/gcp.json
    env_file:
      - ./conn/backend.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp.json
    ports:
      - "8080:80"

  valmary_frontend:
    container_name: valmary_frontend
    build:
      context: app/frontend
      dockerfile: ../../docker/frontend.Dockerfile
      target: dev
    volumes:
      - ./app/frontend/src:/app/src
      - ./app/frontend/index.html:/app/index.html
      - ./app/frontend/package.json:/app/package.json
      - ./app/frontend/package-lock.json:/app/package-lock.json
      - ./app/frontend/vite.config.mjs:/app/vite.config.mjs
      - /app/node_modules
      - /app/.vite
    env_file:
      - ./conn/frontend.env
    environment:
      - VITE_API_URL=http://localhost:8080
    ports:
      - "8081:80"
